import { MenuItemType, SearchResult, SearchSummary } from "./interfaces";

export const DataTypeMenuList: MenuItemType[] = [
  {
    label: 'All',
    value: 'all'
  },
  {
    label: 'Private',
    value: 'private'
  },
  {
    label: 'Public',
    value: 'public'
  },
  {
    label: 'Monetized',
    value: 'monetized'
  },
  {
    label: 'Non-Monetized',
    value: 'nonMonetized'
  },
]

export const TimeRangeMenuList: MenuItemType[] = [
  {
    label: 'Today',
    value: 'today'
  },
  {
    label: 'Last Week',
    value: 'lastWeek'
  },
  {
    label: 'Last Month',
    value: 'lastMonth'
  },
  {
    label: 'Last Year',
    value: 'lastYear'
  },
]

export const ActivityTypesMenuList: MenuItemType[] = [
  { value: "Cryptocurrency", label: "Cryptocurrency" },
  { value: "Comedy", label: "Comedy" },
  { value: "Gaming", label: "Gaming" },
  { value: "Fitness", label: "Fitness" },
  { value: "Photography", label: "Photography" },
  { value: "Fashion", label: "Fashion" },
  { value: "Music", label: "Music" },
  { value: "Movies", label: "Movies" },
  { value: "Travel", label: "Travel" },
  { value: "Blogging", label: "Blogging" },
];

export const SearchResultsSummary: SearchSummary = [
  'Computer programmer.',
  'A well-known job that involves writing computer programs, testing software, and troubleshooting.',
  'Data scientist.',
  'A trending job that involves analyzing large amounts of data.'
]

export const SearchResultsList: SearchResult[] = [
  {
    id: 1,
    title: 'Full Stack Developer (SDE-2)',
    description: 'Work on full-stack projects using React, Node.js, and MongoDB.',
    referenceUrl: 'https://www.dribble.com/jobs/12345',
    isSelected: true,
    isMonetised: true,
    isPublic: true,
    domainName: 'dribble.com',
    icon: 'https://www.dribble.com/favicon.ico',
  },
  {
    id: 2,
    title: 'Frontend Developer',
    description: 'Create responsive web applications using HTML, CSS, and JavaScript.',
    referenceUrl: 'https://www.xyz.com/jobs/123',
    isSelected: true,
    isMonetised: false,
    isPublic: true,
    domainName: 'xyz.com',
    icon: 'https://www.xyz.com/favicon.ico',
  },
  {
    id: 3,
    title: 'Backend Developer',
    description: 'Develop robust backend services with Python and Django.',
    referenceUrl: 'https://www.abc.com/jobs/456',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'abc.com',
    icon: 'https://www.abc.com/favicon.ico',
  },
  {
    id: 4,
    title: 'DevOps Engineer',
    description: 'Manage CI/CD pipelines and cloud infrastructure with AWS.',
    referenceUrl: 'https://www.devopsjobs.com/jobs/789',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'devopsjobs.com',
    icon: 'https://www.devopsjobs.com/favicon.ico',
  },
  {
    id: 5,
    title: 'Mobile App Developer',
    description: 'Build cross-platform mobile apps with Flutter and Dart.',
    referenceUrl: 'https://www.mobiledev.com/jobs/321',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'mobiledev.com',
    icon: 'https://www.mobiledev.com/favicon.ico',
  },
  {
    id: 6,
    title: 'Data Scientist',
    description: 'Analyze large datasets and build predictive models using Python.',
    referenceUrl: 'https://www.datasciencejobs.com/jobs/654',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'datasciencejobs.com',
    icon: 'https://www.datasciencejobs.com/favicon.ico',
  },
  {
    id: 7,
    title: 'Product Manager',
    description: 'Oversee product development from concept to launch.',
    referenceUrl: 'https://www.producthunt.com/jobs/987',
    isSelected: false,
    isMonetised: false,
    isPublic: false,
    domainName: 'producthunt.com',
    icon: 'https://www.producthunt.com/favicon.ico',
  },
  {
    id: 8,
    title: 'UI/UX Designer',
    description: 'Design intuitive user interfaces and experiences.',
    referenceUrl: 'https://www.designerjobs.com/jobs/159',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'designerjobs.com',
    icon: 'https://www.designerjobs.com/favicon.ico',
  },
  {
    id: 9,
    title: 'Cybersecurity Analyst',
    description: 'Protect systems and networks from cyber threats.',
    referenceUrl: 'https://www.cyberjobs.com/jobs/753',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'cyberjobs.com',
    icon: 'https://www.cyberjobs.com/favicon.ico',
  },
  {
    id: 10,
    title: 'Cloud Architect',
    description: 'Design cloud-based solutions using AWS, Azure, and GCP.',
    referenceUrl: 'https://www.cloudjobs.com/jobs/852',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'cloudjobs.com',
    icon: 'https://www.cloudjobs.com/favicon.ico',
  },
  {
    id: 11,
    title: 'Machine Learning Engineer',
    description: 'Implement machine learning models and pipelines.',
    referenceUrl: 'https://www.mljobs.com/jobs/357',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'mljobs.com',
    icon: 'https://www.mljobs.com/favicon.ico',
  },
  {
    id: 12,
    title: 'Technical Writer',
    description: 'Create clear and concise documentation for technical projects.',
    referenceUrl: 'https://www.techwriterjobs.com/jobs/951',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'techwriterjobs.com',
    icon: 'https://www.techwriterjobs.com/favicon.ico',
  },
  {
    id: 13,
    title: 'QA Engineer',
    description: 'Test software applications to ensure quality and performance.',
    referenceUrl: 'https://www.qajobs.com/jobs/753',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'qajobs.com',
    icon: 'https://www.qajobs.com/favicon.ico',
  },
  {
    id: 14,
    title: 'System Administrator',
    description: 'Maintain and monitor server systems and networks.',
    referenceUrl: 'https://www.sysadminjobs.com/jobs/147',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'sysadminjobs.com',
    icon: 'https://www.sysadminjobs.com/favicon.ico',
  },
  {
    id: 15,
    title: 'Salesforce Developer',
    description: 'Develop and customize Salesforce applications.',
    referenceUrl: 'https://www.salesforcejobs.com/jobs/357',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'salesforcejobs.com',
    icon: 'https://www.salesforcejobs.com/favicon.ico',
  },
  {
    id: 16,
    title: 'Game Developer',
    description: 'Create engaging video games using Unity or Unreal Engine.',
    referenceUrl: 'https://www.gamedevs.com/jobs/123',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'gamedevs.com',
    icon: 'https://www.gamedevs.com/favicon.ico',
  },
  {
    id: 17,
    title: 'Blockchain Developer',
    description: 'Develop decentralized applications on blockchain platforms.',
    referenceUrl: 'https://www.blockchainjobs.com/jobs/789',
    isSelected: false,
    isMonetised: true,
    isPublic: false,
    domainName: 'blockchainjobs.com',
    icon: 'https://www.blockchainjobs.com/favicon.ico',
  },
  {
    id: 18,
    title: 'E-commerce Manager',
    description: 'Manage e-commerce platforms and optimize online sales.',
    referenceUrl: 'https://www.ecommercejobs.com/jobs/963',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'ecommercejobs.com',
    icon: 'https://www.ecommercejobs.com/favicon.ico',
  },
  {
    id: 19,
    title: 'IT Support Specialist',
    description: 'Provide technical support and troubleshoot IT issues.',
    referenceUrl: 'https://www.itsupportjobs.com/jobs/456',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'itsupportjobs.com',
    icon: 'https://www.itsupportjobs.com/favicon.ico',
  },
  {
    id: 20,
    title: 'SEO Specialist',
    description: 'Optimize websites to improve search engine rankings.',
    referenceUrl: 'https://www.seojobs.com/jobs/852',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'seojobs.com',
    icon: 'https://www.seojobs.com/favicon.ico',
  },
  {
    id: 21,
    title: 'Content Marketer',
    description: 'Develop and implement content marketing strategies.',
    referenceUrl: 'https://www.contentjobs.com/jobs/951',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'contentjobs.com',
    icon: 'https://www.contentjobs.com/favicon.ico',
  },
  {
    id: 22,
    title: 'Business Analyst',
    description: 'Analyze business needs and recommend IT solutions.',
    referenceUrl: 'https://www.businessanalystjobs.com/jobs/357',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'businessanalystjobs.com',
    icon: 'https://www.businessanalystjobs.com/favicon.ico',
  },
  {
    id: 23,
    title: 'Marketing Manager',
    description: 'Develop and execute marketing strategies for product growth.',
    referenceUrl: 'https://www.marketingjobs.com/jobs/654',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'marketingjobs.com',
    icon: 'https://www.marketingjobs.com/favicon.ico',
  },
  {
    id: 24,
    title: 'Financial Analyst',
    description: 'Analyze financial data to guide investment decisions.',
    referenceUrl: 'https://www.financejobs.com/jobs/852',
    isSelected: false,
    isMonetised: true,
    isPublic: true,
    domainName: 'financejobs.com',
    icon: 'https://www.financejobs.com/favicon.ico',
  },
  {
    id: 25,
    title: 'Customer Success Manager',
    description: 'Ensure customer satisfaction and engagement.',
    referenceUrl: 'https://www.customersuccessjobs.com/jobs/123',
    isSelected: false,
    isMonetised: false,
    isPublic: true,
    domainName: 'customersuccessjobs.com',
    icon: 'https://www.customersuccessjobs.com/favicon.ico',
  },
]
